export CHATBLADE_THEME="autumn"
export COLORTERM="truecolor"
export EDITOR="nvim"
export JAVA_HOME=/usr/lib/jvm/java-17-openjdk
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#7A7A7A"
export ZVM_INSERT_MODE_CURSOR=$ZVM_CURSOR_BLINKING_BLOCK
export ZVM_NORMAL_MODE_CURSOR=$ZVM_CURSOR_BLOCK
export ZVM_OPPEND_MODE_CURSOR=$ZVM_CURSOR_UNDERLINE
