	local map = require('user.utils.map').map

map('i', '<C-c>', '<Esc>', 'Back to normal mode')
map('n', '<leader>w', vim.cmd.update, 'Save buffer')
map('n', '<leader>ay', 'ggVG"+y', 'Select all to system register')
map('n', '<leader>ap', 'ggVG"+p', 'Replace all with system register')
map({ 'n', 'x' }, '<leader>sy', '"+y', 'Yank to system register')
map({ 'n', 'x' }, '<leader>sp', '"+p', 'Paste from system register')
map('n', '<C-h>', '<C-w>h', 'Go to the window on the left')
map('n', '<C-j>', '<C-w>j', 'Go to the window below')
map('n', '<C-k>', '<C-w>k', 'Go to the window above')
map('n', '<C-l>', '<C-w>l', 'Go to the window on the right')
map('n', '<C-Up>', ':resize +1<CR>', 'Increase window height')
map('n', '<C-Down>', ':resize -1<CR>', 'Decrease window height')
map('n', '<C-Left>', ':vertical resize +1<CR>', 'Increase window width')
map('n', '<C-Right>', ':vertical resize -1<CR>', 'Decrease window width')
map('n', '<leader>e', ':Lex 15<cr>', 'Open netrw to the left side')
map('n', '<leader>tt', ':vnew term://zsh<CR>', 'Open zsh to the side')
map('t', '<C-[>', '<C-\\><C-N>', 'Back to normal mode on terminal')
map('t', '<C-h>', '<C-\\><C-N><C-w>h', 'Go to the window on the left')
map('t', '<C-j>', '<C-\\><C-N><C-w>j', 'Go to the window below')
map('t', '<C-k>', '<C-\\><C-N><C-w>k', 'Go to the window above')
map('t', '<C-l>', '<C-\\><C-N><C-w>l', 'Go to the window on the right')

