return {
	{ 'NLKNguyen/papercolor-theme',       as = 'PaperColor'            },
	{ 'NTBBloodbath/sweetie.nvim',        as = 'sweetie'               },
	{ 'ashfinal/vim-colors-paper',        as = 'paper'                 },
	{ 'catppuccin/nvim',                  as = 'catppuccin'            },
	{ 'miikanissi/modus-themes.nvim',     as = 'modus'                 },
	{ 'nyoom-engineering/oxocarbon.nvim', as = 'oxocarbon'             },
	{ 'olimorris/onedarkpro.nvim',        as = 'onedarkpro'            },
	{ 'pappasam/papercolor-theme-slim',   as = 'papercolor-theme-slim' },
	{ 'rebelot/kanagawa.nvim',            as = 'kanagawa'              },
	{ 'rktjmp/lush.nvim',                 as = 'lush'                  },
	{ 'rose-pine/neovim',                 as = 'rose-pine'             },
	{ 'xiyaowong/nvim-transparent',       as = 'transparent'           },
	{ 'yorik1984/newpaper.nvim',          as = 'newpaper'              },
}
